import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aiRouter from "./ai";
import ridesRouter from "./rides";
import adminRouter from "./admin";
import rideAlongDriversRouter from "./rideAlongDrivers";
import stripeConnectRouter from "./stripeConnect";
import tandemJobsRouter from "./tandemJobs";
import tandemMatchingRouter from "./tandemMatching";
import payoutsRouter from "./payouts";
import instantPayoutRouter from "./instantPayout";
import standardPayoutRouter from "./standardPayout";
import deviceTokensRouter from "./deviceTokens";
import devPushTestRouter from "./devPushTest";
import driverLocationRouter from "./driverLocation";
import driverAccountRouter from "./driverAccount";
import debugThrowRouter from "./debugThrow";
import appStatusRouter from "./appStatus";

const router: IRouter = Router();

router.use(healthRouter);
router.use(aiRouter);
router.use(ridesRouter);
router.use(adminRouter);
router.use(rideAlongDriversRouter);
router.use(stripeConnectRouter);
router.use(tandemJobsRouter);
router.use(tandemMatchingRouter);
router.use(payoutsRouter);
router.use(instantPayoutRouter);
router.use(standardPayoutRouter);
router.use(deviceTokensRouter);
router.use(devPushTestRouter);
router.use(driverLocationRouter);
router.use(driverAccountRouter);
router.use(debugThrowRouter);
router.use(appStatusRouter);

export default router;
